[2025-01-06T13:20:02.161+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-06T13:20:02.295+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_quality_checks_dag.check_duplicates_engine_orders scheduled__2025-01-06T00:00:00+00:00 [queued]>
[2025-01-06T13:20:02.312+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_quality_checks_dag.check_duplicates_engine_orders scheduled__2025-01-06T00:00:00+00:00 [queued]>
[2025-01-06T13:20:02.313+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-06T13:20:02.338+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): check_duplicates_engine_orders> on 2025-01-06 00:00:00+00:00
[2025-01-06T13:20:02.379+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=126) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-06T13:20:02.395+0000] {standard_task_runner.py:72} INFO - Started process 144 to run task
[2025-01-06T13:20:02.404+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_quality_checks_dag', 'check_duplicates_engine_orders', 'scheduled__2025-01-06T00:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/Data Quality Checks with Logging.py', '--cfg-path', '/tmp/tmp80d56ldg']
[2025-01-06T13:20:02.412+0000] {standard_task_runner.py:105} INFO - Job 38: Subtask check_duplicates_engine_orders
[2025-01-06T13:20:07.968+0000] {task_command.py:467} INFO - Running <TaskInstance: data_quality_checks_dag.check_duplicates_engine_orders scheduled__2025-01-06T00:00:00+00:00 [running]> on host ff2cd35e75e1
[2025-01-06T13:20:08.612+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_quality_checks_dag' AIRFLOW_CTX_TASK_ID='check_duplicates_engine_orders' AIRFLOW_CTX_EXECUTION_DATE='2025-01-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-06T00:00:00+00:00'
[2025-01-06T13:20:08.652+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-06T13:20:08.656+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-06T13:20:08.659+0000] {logging_mixin.py:190} INFO - Current task name:check_duplicates_engine_orders state:running start_date:2025-01-06 13:20:02.296686+00:00
[2025-01-06T13:20:08.660+0000] {logging_mixin.py:190} INFO - Dag name:data_quality_checks_dag and current dag run status:running
[2025-01-06T13:20:08.671+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-06T13:20:10.159+0000] {logging_mixin.py:190} INFO - No duplicate rows found in table Engine_Orders.
[2025-01-06T13:20:10.174+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-06T13:20:10.403+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-06T13:20:10.407+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=data_quality_checks_dag, task_id=check_duplicates_engine_orders, run_id=scheduled__2025-01-06T00:00:00+00:00, execution_date=20250106T000000, start_date=20250106T132002, end_date=20250106T132010
[2025-01-06T13:20:10.520+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-06T13:20:10.539+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-06T13:20:10.541+0000] {logging_mixin.py:190} INFO - Dag name:data_quality_checks_dag queued_at:2025-01-06 13:19:48.085092+00:00
[2025-01-06T13:20:10.547+0000] {logging_mixin.py:190} INFO - Task hostname:ff2cd35e75e1 operator:PythonOperator
[2025-01-06T13:20:13.326+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-06T13:20:13.453+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-06T13:20:13.468+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
